version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - notification-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - notification-net

networks:
  notification-net:
    driver: bridge

volumes:
  rabbitmq_data: 