apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issue-service
  template:
    metadata:
      labels:
        app: issue-service
    spec:
      containers:
      - name: issue-service
        image: ${DOCKER_REGISTRY}/issue-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: MongoDB__ConnectionString
          value: "mongodb+srv://cefakarberkay:berkay01@campuscation.jtmagbt.mongodb.net/?retryWrites=true&w=majority&appName=CampusCation"
        - name: MongoDB__Database
          value: "IssueDb"
        - name: RabbitMQ__HostName
          value: "rabbitmq"
        - name: RabbitMQ__UserName
          value: "user"
        - name: RabbitMQ__Password
          value: "password"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: issue-service
spec:
  selector:
    app: issue-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 