version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      # Supabase bağlantı bilgileri
      - SUPABASE_DB_HOST=your-supabase-db-host.supabase.co
      - SUPABASE_DB_PORT=5432
      - SUPABASE_DB_NAME=postgres
      - SUPABASE_DB_USER=postgres
      - SUPABASE_DB_PASSWORD=your-password
      # Redis connection
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  rabbitmq_data: 
  redis_data: 