version: "3.8"

services:
  issue-service:
    build:
      context: .           # <── bulunduğu dizin
    container_name: issue-service
    ports:
      - "5240:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      MongoDB__ConnectionString: "mongodb://mongo:27017"
      MongoDB__Database: "IssueDb"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
      RabbitMQ__QueueName: "issue_created"
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - issue-net

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - issue-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - issue-net

networks:
  issue-net:

volumes:
  mongo_data:
  rabbitmq_data:
